version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  configuration: docs/_source/conf.py
  builder: html

python:
  install:
    - requirements: requirements-docs.txt

formats:
  - epub
  - pdf
