[project]
name = "fastchain"
version = "0.1.0"
description = "Chain functions easily and safely"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
keywords = [
    "function",
    "functional",
    "chain",
    "chaining",
    "pipe",
    "piping",
    "pipeline",
    "compose",
    "composing",
    "composition",
    "flow",
    "data",
    "process",
    "processing",
    "safe",
    "node",
    "handle",
    "report"
]
authors = [{name =  "MARSO Adnan" , email = "mediadnan@gmail.com"}]
maintainers = [{name =  "MARSO Adnan" , email = "mediadnan@gmail.com"}]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Information Technology",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development",
    "Topic :: Utilities",
    "Typing :: Typed"
]


[build-system]
requires = ["setuptools>=65.5.1", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=fastchain"
testpaths = [
    "tests"
]

[tool.mypy]
mypy_path = "fastchain"
check_untyped_defs = true
