name: Tests

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/tests.yml
      - funchain/**
      - tests/**
      - requirements.txt
      - pyproject.toml
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Tests 🧪
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} 🐍
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dev Dependencies 📥
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest pytest-asyncio pytest-cov mypy mypy-extensions flake8
      - name : Test with Pytest 🧪
        run: pytest --cov funchain/ --cov-report xml --cov-branch --cov-append
      - name: Upload Coverage to Codecov ☂️
        uses: codecov/codecov-action@v3
        with:
          name: codecov-umbrella
          env_vars: OS,PYTHON
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  style:
    name: Code style 🎨
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11 🐍
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install Dev Dependencies 📥
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install flake8
      - name: Check with flake8 🔎
        run: flake8 funchain

  type:
    name: Static Type 🎨
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11 🐍
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install Dev Dependencies 📥
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install mypy mypy-extensions
      - name: Check with mypy 🔎
        run: mypy funchain